title: EWRL 2022
description: > # this means to ignore newlines until "baseurl:"
  Your description
baseurl: "https://amarildolikmeta.github.io/ewrl2022/" # the subpath of your site, e.g. /blog
url: "https://amarildolikmeta.github.io/ewrl2022/" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2016_style/img/icon-large.png"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: pretty